### ISSUE TITLE
Feature Request - Compatibility with Let's Trade 5e

### ISSUE THREAD

**Issue by bearsy1** [p4535992/foundryvtt-lazymoney-dnd5e#1]
I like your module, nice and simple!

Could this be altered to work seamlessly alongside [Let's Trade 5e](https://foundryvtt.com/packages/lets-trade-5e) ?
It would be very nice if, when trading or sending money to another player or character, the trade window took into account the money sorcery that this module does.

As the trading with that other module works now though, when you enter a coinage amount greater than what you have in that particular denomination in the number/text field (even though you have enough in a higher denomination to convert from) it simply sets the trading amount to the total amount that you have of that coin (which often confuses both parties of the trade as it goes through, but not in the amount either side was expecting).

**Comment by p4535992** [comment]
This is something to ask the author of that module because he is the one in control of the html elements. The code is under a free license so he can copy and paste it for his use case.
