### ISSUE TITLE
[BUG] Error determining currencies when attempting to modify currency values

### ISSUE THREAD

**Issue by ReinhardtGore** [p4535992/foundryvtt-lazymoney-dnd5e#10]
**Module Version:** v1.3.0

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

Error log: [log for error modifying currencies.log](https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/files/14121731/log.for.error.modifying.currencies.log)

**Describe the bug**
When attempting to either add/subtract currencies through either the character sheet or a macro calling the module's API, the following error occurs: `Item Piles | addCurrency | Could not determine currencies to add with string "CP"`. It occurs for all denominations of currency.

**To Reproduce**
1. Navigate to an actor
2. Attempt to change their currency values with a +10

**Expected behavior**
Currency to be modified/converted if applicable

**Screenshots**
![image](https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/assets/31933668/034bb976-6b29-4509-a477-72e1d55696bc)

**Browser:**
 n/a

**Foundry Version:** 
11

**Game System:** 
DnD 5e 2.4.1

**Additional context**
I have tried disabling all modules except for item piles, lazy money, tidyui, and any other dependencies (socketlib & libWrapper), it still occurs.

**Comment by p4535992** [comment]
can you try 1.3.1 and tell me if the issue persist ?

**Comment by ReinhardtGore** [comment]
Perfect, all good once again, thanks!
