### ISSUE TITLE
v12 compatibility

### ISSUE THREAD

**Issue by CaosFR** [p4535992/foundryvtt-lazymoney-dnd5e#11]
Hi,

Do you plan to update to v12 ? The module do not work in v12.

Tested with Foundry, DnD5e update to date. Nothing append if I try to reduce and convert coins (no error in console).

Thanks

**Comment by p4535992** [comment]
It should be working on  v12 did you try ? Therenis any error in the console ?

**Comment by CaosFR** [comment]
Yes of course I had try it before post it. No error in the console (20 gold reduce witn 10 copper no change).

**Comment by p4535992** [comment]
I'll try to find some time after august for refresh all my modules, Sorry for the delay.

**Comment by CaosFR** [comment]
IRL first oc; good luck for the updates.

**Comment by CaosFR** [comment]
Solved it's was a problem with the sheet, not your module. You can update the module.json it's look ol.

**Comment by CaosFR** [comment]
Solved it's was a problem with the sheet, not your module. You can update the module.json it's look ok.
