### ISSUE TITLE
[BUG] Incorrect Calculation on PC Sheets

### ISSUE THREAD

**Issue by KellethDregar** [p4535992/foundryvtt-lazymoney-dnd5e#2]
**Module Version:** v1.0.10

**Describe the bug**
When calculating the amount added or subtracted the final value will usually result in a zero. Sometimes when adding if the added amount is higher than the current amount it will simply replace the current amount with the added amount (5+50=50). It's notable it works fine on NPC sheets just not PC sheets.

**To Reproduce**
1. Select a Coin type
2. Click it and replace the value with +X or -X and hit enter
3. Value will either result in 0 or add

**Expected behavior**
The value will be increased or decreased to a new value.

**Screenshots**
![image](https://user-images.githubusercontent.com/79947702/229425384-7f8a0e21-4144-43cd-b2ee-3c10eed38d2c.png)
![image](https://user-images.githubusercontent.com/79947702/229425721-168fa20b-f1d1-40bc-81d3-f05c9af8aca0.png)
![image](https://user-images.githubusercontent.com/79947702/229425697-f6d0820e-3fca-4977-9ead-44a212f04b26.png)
![image](https://user-images.githubusercontent.com/79947702/229425743-75cad129-0da7-40a2-999b-cec0430feebd.png)

**Browser:**
 -Chrome OS

**Foundry Version:** 
10.291

**Game System:** 
2.1.5

**Additional context**
I am using this in tandem with tidysheet. I'm unsure if this is an issue on that module or this module but it occurs when only one is active too.

**Comment by KellethDregar** [comment]
Still seems to be overriding the amount with the newly entered amount instead of the calculation result.

![image](https://user-images.githubusercontent.com/79947702/230802691-2bb0e3f6-3d84-4042-86f6-8ae8c8708ece.png)
![image](https://user-images.githubusercontent.com/79947702/230802695-c0b96320-8f89-47b7-922c-566479283661.png)
![image](https://user-images.githubusercontent.com/79947702/230802696-0bffa307-fed3-4aa2-9a44-44a428bc8145.png)

**Comment by F1rewind** [comment]
![Initial state](https://user-images.githubusercontent.com/100736590/233871229-7d337c47-c91a-473e-b464-f3b98ee1915a.png)
![adding currency](https://user-images.githubusercontent.com/100736590/233871255-ba0b5e1f-b1e9-4fd7-a0d3-330c62d8b4c0.png)
![final sum](https://user-images.githubusercontent.com/100736590/233871312-9a8134a1-5706-4f23-b106-67f333807c40.png)

Still broken for me. Addition replaces the value instead of adding, and subtraction sets it to 0.

**Comment by KellethDregar** [comment]
Not sure if this helps but i removed the lazy money module entirely and just use lazy money via tidy sheet and it works that way.

**Comment by p4535992** [comment]
The code is literally the same  present on tidysheet (copy and paste ) .
I'm pretty sure is a cache problem on the browser.
I will check out anyway.

**Comment by SirAron111** [comment]
I experience the same issue. The new amount with + simply sets it to the number added after the + and any amount subtracted with a - will just set it to 0.
Maybe it's a conflict with tidy sheet's lazy money option. I disabled lazy money module and simply set it on tidy sheet and it works now.

**Comment by eternaljade2k1** [comment]
Also experiencing this. Hoping to see it updated since there aren't any alternatives for v11.
