### ISSUE TITLE
[BUG] Subtracting coins is producing large amounts of smaller coins

### ISSUE THREAD

**Issue by mfozz** [p4535992/foundryvtt-lazymoney-dnd5e#6]
**Module Version:** v1.1.5

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
Subtracting currency that is 0 adds 1000 coins minus the number (for example, subtracting 5 cp from 0 cp adds 995 cp). If the actor has only 10 sp, subtracting -5 cp produces 995 cp. The calculations tend to be more egregious if the Ignore Electrum option is enabled. 

**To Reproduce**
1. Go to character sheet.
2. Click the Inventory tab.
3. Locate a currency that is 0.
4. Subtract an amount (such as -5).

**Expected behavior**
The calculations should produce correct change.

**Screenshots**
<img width="574" alt="Screenshot 2023-10-17 at 3 56 40 AM" src="https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/assets/89781047/a106cd60-4b72-40bf-9b4b-4e67051f787a">
<img width="572" alt="Screenshot 2023-10-17 at 3 57 05 AM" src="https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/assets/89781047/2762695a-48aa-4a4f-90d1-7c3dd910a447">
<img width="575" alt="Screenshot 2023-10-17 at 3 57 13 AM" src="https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/assets/89781047/c9f008ca-0c25-451d-a318-2b4c4149bc3d">

**Browser:**
 - Chrome Version 117.0.5938.149
 - Firefox 118.0.2

**Foundry Version: 11.3.1.3

**Game System: DND5e 2.3.1

**Additional context**
I have all other modules disabled for testing. 
[shayulghul-test1.forge-vtt.com-1697532508216.log](https://github.com/p4535992/foundryvtt-lazymoney-dnd5e/files/12926598/shayulghul-test1.forge-vtt.com-1697532508216.log)

**Comment by mfozz** [comment]
The update fixed the issue. Thanks for the quick update!

**Comment by p4535992** [comment]
wait is working ? are you sure ? now is not working for me O.O

**Comment by mfozz** [comment]
Yeah, I just double-checked in my test game. It seems to be working fine for me after the update.
